### ISSUE TITLE
CyberScout

### ISSUE THREAD

**Issue by sec13b** [iojaiustin/evilholmes#1]
what happen with CyberScout

**Comment by iojaiustin** [comment]
The free server I had was overwhelmed and couldn't handle all the requests at once. For now, I have to bring some improvements to the project and find a more reliable server to host it. Thanks for being interested.

**Comment by sec13b** [comment]
can you upload the project , id someone want test , may use personal server.

**Comment by iojaiustin** [comment]
I'm going to publish a copy of CyberScout as a directory on my profile. You will need to create a telegram bot on your own by using BotFather (https://telegram.me/BotFather). The directory may come with unfinished work that can raise errors. For support, please email me at ioja.iustin@gmail.com. All you have to do after replacing your id's and api's is to run telegrambot.py
